language: R
sudo: false
cache: packages

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e "covr::codecov()"
  
r_github_packages:
  - MangoTheCat/goodpractice

after_success:
  - Rscript -e "goodpractice::gp()"
