# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculate the sum
#' @param values the values to sum
#' @return the sum
#' @author Richèl J.C. Bilderbeek
calc_sum_cpp <- function(values) {
    .Call('cirthree_calc_sum_cpp', PACKAGE = 'cirthree', values)
}

#' Get proper divisors
#' @param n the number to euvfwekyb
#' @return the proper divisors
#' @author Richèl J.C. Bilderbeek
get_proper_divisors <- function(n) {
    .Call('cirthree_get_proper_divisors', PACKAGE = 'cirthree', n)
}

